#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

### STARTUP ####

## Variables ##
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod									# Use alt as the main modifier
Mod=Mod4									# Use the super key as the main modifier

wallpaper=~/Pictures/autumnwallpaper.jpg
trackpad='SYNA2393:00 06CB:7A13 Touchpad'


## Polybar
#panel=~/.config/polybar/launch.sh			# turn on for polybar
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
	# start it on each monitor
	"$panel" $monitor &
	hc pad $monitor 0 0 0 0 # TOP RGT BTM LFT
done

## Theming ##
dblue='#00203b'
lblue='#0074d8'
bgrey='#6791a2'
egg='#edf2f4'
pwhite='#ffffff'
pblack='#000000'
	# fill these in later
border='#6791a2'
	# innerborder=
	# outerborder=

# Wallpaper
hc spawn feh --bg-scale $wallpaper

# Trackpad
#setprop=sudo xinput --set-prop $trackpad
#hc spawn $setprop "libinput Tapping Enabled" 1
#hc spawn $setprop "libinput Tapping Enabled Default" 1
#hc spawn $setprop "libinput Natural Scrolling Enabled" 1

hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Tapping Enabled" 1
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Tapping Enabled Default" 1
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Natural Scrolling Enabled" 1
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Natural Scrolling Enabled Default" 1
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Middle Emulation Enabled" 1
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Middle Emulation Enabled Default" 1
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Drag Enabled" 1 
hc spawn sudo xinput set-prop 'SYNA2393:00 06CB:7A13 Touchpad' "libinput Disable While Typing Enabled" 1

# Misc
hc spawn compton

# turn on once fix for spotify class name not working for tab switching
#  hc spawn pavucontrol
#  spawn spotify

### KEYBINDS ###

# remove all existing keybindings
hc keyunbind --all

## My Bindings ##

# DWM
hc keybind $Mod+Alt+d wmexec dwm

# Lockscreen
hc keybind $Mod-Control-q spawn i3lock -u -i ~/Pictures/autumnwallpaper.png

## Applications ##
hc keybind $Mod-d spawn rofi -show run
hc keybind $Mod-b spawn google-chrome-stable
hc keybind $Mod-Shift-b spawn firefox
hc keybind $Mod-v spawn code
hc keybind $Mod-Alt-v spawn eclipse

# audio
hc keybind XF86AudioRaiseVolume spawn amixer set -q Master 5%+
hc keybind XF86AudioLowerVolume spawn amixer set -q Master 5%-
hc keybind $Mod-XF86AudioRaiseVolume spawn amixer set -q Master 1%+
hc keybind $Mod-XF86AudioLowerVolume spawn amixer set -q Master 1%-
hc keybind $Mod-Shift-XF86AudioRaiseVolume spawn amixer set -q Master 10%+
hc keybind $Mod-Shift-XF86AudioLowerVolume spawn amixer set -q Master 10%-
hc keybind XF86AudioMute spawn amixer set Master toggle

# brightness
hc keybind XF86MonBrightnessUp spawn sudo light -A 5
hc keybind XF86MonBrightnessDown spawn sudo light -U 5
hc keybind $Mod-XF86MonBrightnessUp spawn sudo light -A 1
hc keybind $Mod-XF86MonBrightnessDown spawn sudo light -U 1
hc keybind $Mod-Shift-XF86MonBrightnessUp spawn sudo light -A 10
hc keybind $Mod-Shift-XF86MonBrightnessDown spawn sudo light -U 10

## Toggle Polybar ON/OFF
hc keybind $Mod-n spawn ~/.config/herbstluftwm/off.sh
hc keybind $Mod-Shift-n spawn ~/.config/herbstluftwm/on.sh


## Default Bindings ##

hc keybind $Mod-Shift-p herbstclient quit
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
#hc keybind $Mod-Return spawn ${TERMINAL:-urxvt} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Return spawn ${TERMINAL:-st} # use your $TERMINAL with xterm as fallback


# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Media
hc keybind XF86AudioPlay spawn playerctl play
hc keybind XF86AudioPause spawn playerctl pause
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn  playerctl previous


# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

### RICING ###

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $bgrey		# $pwhite
hc set frame_border_normal_color $pblack	# '#101010'
hc set frame_bg_normal_color $pblack		# '#565656'
hc set frame_bg_active_color $bgrey			# '#345F0C'
# hc set frame_border_inner_color $bgrey
hc set frame_border_width 0
hc set frame_border_inner_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color $border			# '#ea734b'
hc attr theme.normal.color $dblue			# '#454545'
hc attr theme.urgent.color $lblue			# orange
hc attr theme.inner_width 0					# 1
hc attr theme.inner_color black				# black	
hc attr theme.border_width 0				# 3
hc attr theme.floating.border_width	0		# 4
hc attr theme.floating.outer_width 0		# 1
hc attr theme.floating.outer_color black	# black
hc attr theme.active.inner_color $border # '#000000'		# '#3E4A00'
hc attr theme.active.outer_color $border # '#000000'		# '#3E4A00'
hc attr theme.background_color '#141414'		# '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

### RULES ###

hc unrule -F

#hc rule class=XTerm tag=3			# move all xterms to tag 3

#hc rule class=Spotify tag=9		# supposed to move spotify to tab 9...

#hc rule instance=pavu-control tag=9	# Moves pavucontrol to tab 9

hc rule focus=on					# normally focus new clients
#hc rule focus=off					# normally do not focus new clients

# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:

while [[ $(hc list_monitors | wc -l) -gt 1 ]]; do
    hc remove_monitor 1
done

# tags
NUM_MONS=$(xrandr --current | grep "^\w.* connected" | wc -l)
MON_RES=( $(xrandr --current | grep "^\w.* connected" | awk '{print $3}') )
MON_NUMS=$( python -c "for i in range(${NUM_MONS}): print(i)" )

for i in ${MON_NUMS[@]} ; do
    echo "${i}"
    if [[ $i == '0' ]]; then
        hc move_monitor $i ${MON_RES[$i]};
    else
        hc add_monitor ${MON_RES[$i]};
    fi
done

hc detect_monitors
